# Generated by Django 5.1.4 on 2024-12-08 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
                ('edad', models.CharField()),
                ('direccion', models.CharField()),
                ('telefono', models.BigIntegerField()),
                ('f_n', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='juegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='c_j',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bennyapp.clientes')),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bennyapp.juegos')),
            ],
        ),
        migrations.CreateModel(
            name='j_p',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bennyapp.juegos')),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bennyapp.plataforma')),
            ],
        ),
    ]
