# Generated by Django 5.1.4 on 2024-12-09 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bennyapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='clientes',
            new_name='cliente',
        ),
        migrations.RenameModel(
            old_name='juegos',
            new_name='juego',
        ),
    ]
